LoanApp/urls.py
from django.urls import path
from LoanApp import views

app_name = 'LoanApp'

urlpatterns =[
    path('loan-request/', views.LoanRequest, name='loan_request'),
    path('loan-repayment/', views.LoanPayment, name='loan_payment'),
    path('user-transaction/', views.UserTransaction, name= 'user_transaction'),
    path('user-loan-history/', views.UserLoanHistory, name='user_loan_history'),
    path('user-dashboard/',views.UserDashboard, name='user_dashboard'),
    

]

LoanManagementSytem/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from LoanApp import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('account/', include('LoginApp.urls')),
    path('manager/', include('ManagerApp.urls')),
    path('loan/', include('LoanApp.urls')),

]

urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
handler404 ='LoanApp.views.error_404_view'

LoginApp/urls.py
from django.urls import path
from LoginApp import views

app_name= 'login_app'

urlpatterns = [
    path('login-customer',views.login_view, name='login_customer'),
    path('signup-customer',views.sign_up_view, name='signup_customer'),
    path('logout-customer',views.logout_view, name='logout'),
    path('edit-customer', views.edit_customer, name='edit_customer'),

] 

ManagerApp/urls.py
from django.urls import path
from ManagerApp import views

app_name = 'ManagerApp'

urlpatterns = [
    path('admin-login/', views.super_login_view, name='admin_login'),
    path('dashboard/', views.dashboard, name ='dashboard'),
    path('add-category/', views.add_category, name='add_category'),
    path('users/', views.total_users , name='total_users'),
    path('user-remove/<int:pk>/', views.user_remove, name='user_remove'),
    path('loan-request-user/', views.loan_request , name='loan_request'),
    path('approved-request/<int:id>/', views.approved_request, name='approved_request'),
    path('rejected-request/<int:id>/', views.rejected_request, name='rejected_request'),
    path('approved-loan', views.approved_loan, name='approved_loan'),
    path('rejected-loan', views.rejected_loan, name='rejected_loan'),
    path('transaction-loan', views.transaction_loan, name='transaction_loan'),


]

templates/base.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/735bf95db2.js" crossorigin="anonymous"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
    
    <title> Loan Management System </title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <style>
        .row{
            height:80vh;
        }
    </style>
</head>
<body>
    <div>
        {% include 'navbar.html' %} 
        {% block content %} 
        {% endblock content %}
        {% include 'scripts.html' %}
        {% include 'footer.html' %} 
    </div>
    
</body>
</html>

templates/error.html
{% extends 'base.html' %}

{% block content %}
<div class="my-5 conatiner">
    <div class="row">
        <div class="m-auto col-md-4">
            <div class="text-center alert alert-danger" role="alert">
                {{error}}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/footer.html
<footer class="text-center text-white bg-light">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
                <!-- Section: Social media -->
                <section class="mb-4">
                        <!-- Facebook -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #3b5998;" href="#!"
                                role="button"><i class="fab fa-facebook-f"></i></a>

                        <!-- Twitter -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #55acee;" href="#!"
                                role="button"><i class="fab fa-twitter"></i></a>

                        <!-- Google -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #dd4b39;" href="#!"
                                role="button"><i class="fab fa-google"></i></a>

                        <!-- Instagram -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #ac2bac;" href="#!"
                                role="button"><i class="fab fa-instagram"></i></a>

                        <!-- Linkedin -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #0082ca;" href="#!"
                                role="button"><i class="fab fa-linkedin-in"></i></a>
                        <!-- Github -->
                        <a class="m-1 btn btn-primary btn-floating" style="background-color: #333333;" href="#!"
                                role="button"><i class="fab fa-github"></i></a>
                </section>
                <!-- Section: Social media -->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="p-3 text-center text-dark" style="background-color: rgba(0, 0, 0, 0.2);">
                © 2021 Copyright
                <a class="text-dark" >LMS</a>
        </div>
        <!-- Copyright -->
</footer>

templates/home.html
{% extends 'base.html'%}

<style>
    .row{
        height:80vh;
    }
    

    .col-md-6-auto{
        background-image: url('https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80');
        background-repeat: no-repeat;
    }

    

</style>

{% block content %}
<div class="container" style="background-image: url('https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80');background-repeat: no-repeat;background-size: cover;">
    
    <div class="row">
        <div>
            <p style="text-align: center"> <br>Trusted by over 600 Lending Companies Worldwide </p>
            <p><h6>1.Charts and Reports.</h6>
                View detailed charts and see how your loan released and collections are changing month to month. You can also view cash flow reports and profit/loss statements.
                This will allow you to instantly see your business performance through graphic charts and take informed decisions.
            <h6>2.View loan details</h6>
                Including repayments, loan terms, loan schedule, collateral, files, and comments. You can also print loan statements and schedule for your borrowers. Set loan fees, and penalties.
                Create savings account for your borrowers and investor accounts for your investors. Add transactions such as deposits and withdrawals. You can also download and print statements.
                The system will automatically add interest to the account depending on your product settings.
            <h6>3.Auto-fill Loan Application and Agreements </h6>
                The system will then replace those placeholders with data from the loan..
                You can download the filled agreement in DOCX and PDF or send it via email or for E-Signature to the borrower.
            </p> 
        </div>
        <div class="col-md-6-auto">
           <p>Welcome Dear {{User}}<p/>
            <!-- <img class="img-fluid mx-auto" alt="Bckground Image" src="https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80"> -->

        </div>
        <div class="col-md-6-auto">
                <!--<img class="img-fluid mx-auto" alt="Bckground Image" src="https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80">-->

        </div>
        <div class="col-md-6-auto">
            <div class="d-flex justify-content align-items-center" >
                <a href="/loan/loan-request/">
                    <button type="button" class="btn btn-info btn-rounded m-2">Apply for a Loan</button>
                </a>

                or

                <a href="/account/signup-customer/">
                    <button type="button" class ="btn btn-info btn-rounded m-2">Register</button>
                </a>

            </div>
        </div>    
    </div>

</div>

{% endblock content %} 


            

templates/navbar.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">=
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
    <!-- MDB -->

    <title></title>

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Navbar brand -->
                <a class="mt-2 navbar-brand mt-lg-0" href="/">
                    <img src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png" height="15" alt=""
                        loading="lazy" />
                </a>

                <!-- Left links -->
                <ul class="mb-2 navbar-nav me-auto mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href=" {% url 'LoanApp:user_dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=" {% url 'LoanApp:user_loan_history' %}">Loan History</a>
                    </li>
                    <li class="nav-item">
                        
                        <a class="nav-link" href=" {% url 'LoanApp:loan_payment' %}">Pay Loan</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=" {% url 'LoanApp:user_transaction' %}">Transactions</a>
                    </li>
                    {% endif %}

                </ul>
                <!-- Left links -->

                <ul class="mb-2 navbar-nav ms-auto mb-lg-0">
                    {% if user.is_authenticated %}

                    <li>
                       
                        <a class="nav-link" href="{% url 'LoanApp:loan_request' %}">Apply Loan</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'login_app:edit_customer' %}">Edit Info</a>
                    </li>

                    <li>
                        <a class="nav-link" href="{% url 'login_app:logout' %}">Logout</a>
                    </li>
                    <li>
                        <i class='fas'>&#xf2bd;{{user}}/Role</i>
                    </li>
                    {% else %}
                    <li class="nav-item me-2">
                        <b> <a class="nav-link" href="{% url 'login_app:login_customer' %}">Login</a></b>
                    </li>
                    <li class="nav-item">
                        <b> <a class="nav-link" href="{% url 'login_app:signup_customer' %}">Signup</a></b>
                    </li>
                    <li class="nav-item">
                        <b> <a class="nav-link" href="{% url 'ManagerApp:admin_login' %}">Admin Login</a></b>
                    </li>
                    

                    {% endif %}

                </ul>
            </div>
            <!-- Collapsible wrapper -->

            <!-- Right elements -->
            <div class="d-flex align-items-center">

            </div>
            <!-- Right elements -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>

</body>

</html>




                

templates/notFound.html
{% extends 'base.html' %}

{% block content %}

<header class='container'>
<!-- Jumbotron -->
<div class="p-5 text-center alert alert-danger" role="alert">
    <h1 class="mb-3">Page Not Found</h1>
    <h4 class="mb-3">Sorry the page is missing or doesn't exist</h4>
    <a class="btn btn-primary" href="/" role="button">Home Page</a>
</div>
<!-- Jumbotron -->
</header>
{% endblock content %}

templates/plugin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/735bf95db2.js" crossorigin="anonymous"></script>

        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
        <!-- MDB -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script> 
    </head>

    <body>
        {% include "scripts.html" %}
    </body>
</html>

templates/scripts.html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>